version: '3.9'
services:
  postgres_db:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin_ui:
    container_name: pg_admin_container
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tber@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: